# Generated by Django 4.1.4 on 2022-12-14 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field='height', null=True, upload_to='photos', width_field='width')),
                ('title', models.CharField(max_length=120, verbose_name='наименование фото')),
                ('geo_position', models.CharField(blank=True, max_length=400, null=True, verbose_name='геопозиция')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('names_people_photo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имена людей на фото')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='app.user')),
            ],
        ),
    ]
